import { StyleSheet } from 'react-native';
import { wp, hp, rf, rs } from '../utils/responsive';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FDF8E1',
  },
  container: {
    flex: 1,
    backgroundColor: '#FFFCF1',
  },
  backButton: {
    position: 'absolute',
    top: hp(50),
    left: wp(10),
    zIndex: 10,
    padding: wp(8),
    marginBottom: hp(19),
  },
  backButtonImage: {
    width: rf(24),
    height: rf(24),
    tintColor: '#000000',
  },
  contentContainer: {
    flex: 1,
    paddingTop: hp(109),
    paddingHorizontal: wp(20),
    paddingBottom: 0,
  },
  heading: {
    fontSize: rf(18),
    fontFamily: 'GTMaruBold',
   
    color: '#000000',
    lineHeight: rf(28),
    marginBottom: hp(12),
  },
  highlightedText: {
    color: '#F9DC5C',
    fontFamily: 'GTMaruBold',
  },
  subHeading: {
    fontSize: rf(14),
    fontFamily: '',
    fontWeight: '400',
    color: '#666666',
    marginBottom: hp(24),
  },
  accountsContainer: {
    flex: 1,
  },
  accountCard: {
    borderColor: '#FEFFAF',
    borderWidth: 2,
    borderRadius: rs(24),
    padding: wp(16),
    marginBottom: hp(16),
    marginHorizontal: wp(4),
    position: 'relative',
    overflow: 'hidden',
  },
  accountCardSelected: {
    backgroundColor: '#FEFFAF',
    borderRadius: rs(24),
    shadowColor: '#FDDA0D',
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 5,
  },
  newAccountCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: rs(24),
  },
  accountHeader: {
    marginBottom: hp(8),
  },
  createdDate: {
    fontSize: rf(11),
    fontFamily: 'Inter',
    fontWeight: '400',
    color: '#666666',
  },
  accountBody: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileImageContainer: {
    marginRight: wp(12),
  },
  profileImagePlaceholder: {
    width: rf(50),
    height: rf(50),
    borderRadius: rf(25),
    backgroundColor: '#E3F2FD',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  profileIcon: {
    width: rf(35),
    height: rf(35),
  },
  accountInfo: {
    flex: 1,
  },
  accountName: {
    fontSize: rf(16),
    fontFamily: 'GTMaruBold',
    color: '#000000',
    marginBottom: hp(4),
  },
  accountLogin: {
    fontSize: rf(13),
    fontFamily: 'Inter',
    fontWeight: '400',
   
  },
  newAccountText: {
    fontSize: rf(16),
    fontFamily: 'GTMaruBold',
    color: '#000000',
    marginBottom: hp(4),
  },
  selectionIndicator: {
    position: 'absolute',
    top: wp(12),
    right: wp(12),
    width: rf(20),
    height: rf(20),
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkIconContainer: {
    width: rf(20),
    height: rf(20),
    borderRadius: rf(10),
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkIcon: {
    width: rf(12),
    height: rf(12),
  },
  radioButton: {
    width: rf(20),
    height: rf(20),
    borderRadius: rf(10),
    borderWidth: 2,
    borderColor: '#CFD8DC',
  },
  separatorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: hp(12),
  },
  separatorLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#CFD8DC',
  },
  separatorText: {
    paddingHorizontal: wp(12),
    fontSize: rf(13),
    fontFamily: 'Inter',
    fontWeight: '400',
    color: '#90A4AE',
  },
  footerContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderTopLeftRadius: rs(30),
    borderTopRightRadius: rs(30),
    paddingTop: hp(28),
    paddingHorizontal: wp(24),
    paddingBottom: hp(40),
    marginHorizontal: wp(-20),
    marginTop: hp(24),
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.2,
    shadowRadius: 25,
    elevation: 15,
    overflow: 'hidden',
  },
  footerText: {
    fontSize: rf(12),
    fontFamily: 'Inter',
    fontWeight: '400',
    color: '#000000',
    textAlign: 'center',
    marginBottom: hp(20),
    lineHeight: rf(18),
  },
  continueButton: {
    width: '100%',
    height: hp(50),
    fontWeight: 'bold',
    backgroundColor: '#FDFF8E',
    borderRadius: rs(12),
   
    justifyContent: 'center',
    alignItems: 'center',
  },
  continueButtonText: {
    fontSize: rf(16),
    fontFamily: 'GTMaruBold',
    color: 'black',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContentWrapper: {
    position: 'relative',
    marginTop: hp(15),
    marginBottom: hp(13),
    marginLeft: wp(20),
    marginRight: wp(20),
    alignSelf: 'center',
    borderRadius: rs(39),
    overflow: 'hidden',
  },
  modalBlurLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#FDFF8E',
    borderTopLeftRadius: rs(30),
    borderTopRightRadius: rs(30),
    borderBottomLeftRadius: rs(30),
    borderBottomRightRadius: rs(30),
    borderTopWidth: 1.5,
    borderBottomWidth: 1.5,
    borderLeftWidth: 1.5,
    borderRightWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  modalContent: {
    backgroundColor: '#FFFCF1',
    borderTopLeftRadius: rs(30),
    borderTopRightRadius: rs(30),
    borderBottomLeftRadius: rs(30),
    borderBottomRightRadius: rs(30),
    paddingTop: hp(16),
    paddingHorizontal: wp(24),
    paddingBottom: hp(20),
    alignItems: 'center',
    borderTopWidth: 1.5,
    borderBottomWidth: 1.5,
    borderLeftWidth: 1.5,
    borderRightWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.1,
    shadowRadius: 30,
    elevation: 15,
    overflow: 'hidden',
  },
  modalIconContainer: {
    marginBottom: hp(12),
  },
  modalIcon: {
    width: rf(70),
    height: rf(70),
    borderRadius: rf(35),
    backgroundColor: '#E3F2FD',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalProfileIcon: {
    width: rf(42),
    height: rf(42),
  },
  modalHeading: {
    fontSize: rf(16),
    fontFamily: 'GTMaruBold',
    color: '#000000',
    textAlign: 'center',
    marginBottom: hp(10),
    lineHeight: rf(22),
    textShadowColor: 'rgba(255, 255, 255, 0.8)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  modalHighlightedText: {
    color: '#f9dc5c',
    fontFamily: 'GTMaruBold',
  },
  modalWarning: {
    fontSize: rf(14),
    fontFamily: 'Inter',
    fontWeight: '400',
    color: '#666666',
    textAlign: 'center',
    marginBottom: hp(16),
    lineHeight: rf(20),
    textShadowColor: 'rgba(255, 255, 255, 0.8)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  modalButton: {
    width: '100%',
    height: hp(56),
    fontFamily: 'GTMaruBold',
    borderRadius: rs(28),
    backgroundColor: '#FDFF8E',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalButtonText: {
    fontSize: rf(18),
    fontFamily: 'GTMaruBold',
    color: 'black',
  },
});

export default styles;

