import { StyleSheet } from 'react-native';
import { wp, hp, rf, rs } from '../utils/responsive';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFCF1',
  },
  backButton: {
    position: 'absolute',
    top: hp(20),
    left: wp(20),
    zIndex: 10,
    width: rf(44),
    height: rf(44),
    borderRadius: rf(22),
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginTop: hp(30),
  },
  backButtonText: {
    fontSize: rf(24),
    color: '#000000',
    fontFamily: 'GTMaruBold',
  },
  content: {
    flex: 1,
    paddingHorizontal: wp(24),
    paddingTop: hp(120),
    paddingBottom: hp(100),
  },
  header: {
    alignItems: 'flex-start',
    marginBottom: hp(40),
  },
  title: {
    fontSize: rf(24),
    fontFamily: 'GTMaruBold',
    color: '#000000',
  },
  inputSection: {
    marginBottom: hp(40),
  },
  glassInput: {
    width: '100%',
    borderRadius: rs(23),
    borderWidth: 2,
    borderColor: '#FDFF8D',
    overflow: 'hidden',
    marginBottom: hp(16),
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
  },
  glassFallback: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(0, 0, 0, 0.1)',
  },
  phoneInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(20),
    paddingVertical: hp(18),
    borderColor: '#FDFF8D',
    borderRadius: rs(10),
  },
  countryCode: {
    fontSize: rf(18),
    fontFamily: 'GTMaruBold',
    color: '#000000',
    marginRight: wp(12),
  },
  phoneInput: {
    flex: 1,
    fontSize: rf(18),
    fontFamily: 'GTMaruRegular',
    color: '#000000',
    padding: 0,
  },
  otpContainer: {
    marginTop: hp(8),
  },
  otpInput: {
    fontSize: rf(18),
    fontFamily: 'GTMaruRegular',
    color: '#000000',
    paddingHorizontal: wp(20),
    paddingVertical: hp(18),
    textAlign: 'center',
    letterSpacing: rs(4),
  },
  continueButton: {
    width: '100%',
    height: hp(56),
    borderRadius: rs(28),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: hp(8),
    overflow: 'hidden',
    shadowColor: '#ffffff',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  continueButtonActive: {
    backgroundColor: '#FDFF8D',
  },
  continueButtonInactive: {
    backgroundColor: '#E0E0E0',
  },
  continueButtonText: {
    fontSize: rf(18),
    fontFamily: 'GTMaruBold',
    color: '#000000',
    letterSpacing: rs(0.5),
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: hp(30),
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
  },
  dividerText: {
    fontSize: rf(14),
    fontFamily: 'GTMaruRegular',
    color: '#666666',
    marginHorizontal: wp(16),
  },
  socialButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: wp(16),
    marginBottom: hp(40),
  },
  socialButtonGlass: {
    flex: 1,
    borderRadius: rs(30),
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  socialButton: {
    flex: 1,
    height: hp(56),
    borderRadius: rs(30),
    overflow: 'hidden',
  },
  socialButtonGradient: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: wp(10),
    paddingHorizontal: wp(16),
  },
  socialButtonFallback: {
    backgroundColor: '#fffcf1',
    borderWidth: 1.5,
    borderColor: 'rgba(0, 0, 0, 0.1)',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: wp(10),
    paddingHorizontal: wp(16),
  },
  socialIcon: {
    width: rf(24),
    height: rf(24),
  },
  socialButtonText: {
    fontSize: rf(16),
    fontFamily: 'GTMaruBold',
    color: '#000000',
  },
  termsContainer: {
    position: 'absolute',
    bottom: hp(30),
    left: 0,
    right: 0,
    alignItems: 'center',
    paddingHorizontal: wp(24),
  },
  termsText: {
    fontSize: rf(12),
    fontFamily: 'GTMaruRegular',
    color: '#666666',
    textAlign: 'center',
    lineHeight: rf(18),
  },
  termsLink: {
    color: '#000000',
    fontFamily: 'GTMaruBold',
    textDecorationLine: 'underline',
  },
});

export default styles;

