import { StyleSheet } from 'react-native';
import { wp, hp, rf, rs } from '../utils/responsive';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FFFCF1',
  },
  container: {
    flex: 1,
    backgroundColor: '#FFFCF1',
  },
  progressBarContainer: {
    width: '90%',
    height: hp(9),
    borderRadius: 30,
    backgroundColor: '#FFFFFF',
    marginTop: hp(70),
    alignSelf: 'center',
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    backgroundColor: '#FDFF8E',
    borderTopLeftRadius: 30,
    borderBottomLeftRadius: 30,
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: wp(24),
    paddingTop: hp(40),
    justifyContent: 'flex-start',
  },
  headingContainer: {
    marginBottom: hp(40),
  },
  heading: {
    fontSize: rf(22),
    fontFamily: 'GTMaruBold',
    color: '#000000',
    lineHeight: rf(31),
    marginBottom: hp(8),
  },
  subheading: {
    fontSize: rf(16),
    fontFamily: 'GTMaruRegular',
    color: '#666666',
    lineHeight: rf(24),
  },
  optionsContainer: {
    marginBottom: hp(32),
  },
  genderOption: {
    width: '100%',
    height: hp(64),
    backgroundColor: '#FFFFFF',
    borderRadius: rs(16),
    borderWidth: 2,
    borderColor: '#FEFFAF',
    marginBottom: hp(16),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: wp(20),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  genderOptionSelected: {
    backgroundColor: '#FDFF8E',
    borderColor: '#FDFF8E',
    borderWidth: 2,
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  genderOptionText: {
    fontSize: rf(18),
    fontFamily: 'GTMaruBold',
    color: '#000000',
  },
  genderOptionTextSelected: {
    color: '#000000',
  },
  genderOptionImage: {
    width: wp(40),
    height: hp(40),
  },
  buttonContainer: {
    marginTop: hp(24),
    marginBottom: hp(32),
    width: '100%',
  },
  continueButton: {
    width: '100%',
    height: hp(50),
    fontWeight: 'bold',
    backgroundColor: '#FDFF8E',
    borderRadius: rs(12),
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  continueButtonDisabled: {
    backgroundColor: '#E0E0E0',
    shadowOpacity: 0,
    elevation: 0,
  },
  continueButtonText: {
    fontSize: rf(18),
    fontFamily: 'GTMaruBold',
    color: 'black',
  },
  continueButtonTextDisabled: {
    color: '#999999',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: wp(24),
  },
  popupContainer: {
    width: '100%',
    maxWidth: wp(320),
    backgroundColor: '#FFFFFF',
    borderRadius: rs(24),
    paddingVertical: hp(32),
    paddingHorizontal: wp(24),
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 8,
  },
  popupIconContainer: {
    width: wp(80),
    height: wp(80),
    borderRadius: wp(40),
    backgroundColor: '#FDFF8E',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: hp(24),
    borderWidth: 3,
    borderColor: '#FEFFAF',
  },
  popupIcon: {
    width: wp(50),
    height: wp(50),
    tintColor: '#000000',
  },
  popupTitle: {
    fontSize: rf(22),
    fontFamily: 'GTMaruBold',
    color: '#000000',
    textAlign: 'center',
    marginBottom: hp(16),
    lineHeight: rf(32),
  },
  popupTitleHighlight: {
    color: '#000000',
  },
  popupMessage: {
    fontSize: rf(14),
    fontFamily: 'GTMaruRegular',
    color: '#666666',
    textAlign: 'center',
    marginBottom: hp(32),
    lineHeight: rf(20),
    paddingHorizontal: wp(8),
  },
  popupButtonsContainer: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    gap: wp(12),
  },
  popupButtonNo: {
    flex: 1,
    height: hp(48),
    backgroundColor: '#FFFFFF',
    borderRadius: rs(12),
    borderWidth: 2,
    borderColor: '#FEFFAF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  popupButtonNoText: {
    fontSize: rf(16),
    fontFamily: 'GTMaruBold',
    color: '#000000',
  },
  popupButtonYes: {
    flex: 1,
    height: hp(48),
    backgroundColor: '#FDFF8E',
    borderRadius: rs(12),
    borderWidth: 2,
    borderColor: '#FDFF8E',
    justifyContent: 'center',
    alignItems: 'center',
  },
  popupButtonYesText: {
    fontSize: rf(16),
    fontFamily: 'GTMaruBold',
    color: '#000000',
  },
});

export default styles;

