import { StyleSheet } from 'react-native';
import { wp, hp, rf, rs } from '../utils/responsive';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  backgroundVideo: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
    width: '100%',
    height: '100%',
  },
  overlayContainer: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  contentContainer: {
    flex: 1,
    justifyContent: 'space-between',
  },
  topSection: {
    alignItems: 'center',
    paddingTop: hp(50),
    marginTop: hp(20),
    paddingHorizontal: wp(20),
  },
  appTitle: {
    fontSize: rf(52),
    fontFamily: 'Inter',
    fontWeight: '900',
    color: '#FFFFFF',
    textShadowColor: '#000000',
    textShadowOffset: { width: 4, height: 4 },
    textShadowRadius: 0,
    letterSpacing: rs(5),
    textAlign: 'center',
    textTransform: 'uppercase',
    includeFontPadding: false,
  },
  appTitleContainer: {
    transform: [{ rotate: '2deg' }],
  },
  bottomOverlayContainer: {
    width: '100%',
    marginTop: 'auto',
    alignItems: 'center',
    paddingHorizontal: wp(20),
    paddingTop: hp(20),
    paddingBottom: hp(20),
  },
  bottomOverlay: {
    width: '100%',
    borderRadius: rs(30),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.18)',
    overflow: 'hidden',
  },
  glassFallback: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  gradientOverlay: {
    paddingTop: hp(30),
    paddingBottom: hp(40),
    paddingHorizontal: wp(24),
    width: '100%',
  },
  metricsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: hp(32),
    gap: wp(16),
  },
  metricBox: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    borderRadius: rs(16),
    paddingVertical: hp(16),
    paddingHorizontal: wp(16),
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  metricIcon: {
    width: rf(24),
    height: rf(24),
    marginBottom: hp(8),
  },
  metricValue: {
    fontSize: rf(24),
    fontFamily: 'Inter',
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: hp(4),
  },
  metricLabel: {
    fontSize: rf(12),
    fontFamily: 'Inter',
    fontWeight: '400',
    color: '#FFFFFF',
    textAlign: 'center',
    opacity: 0.9,
  },
  headingContainer: {
    alignItems: 'center',
    marginBottom: hp(28),
  },
  heading: {
    fontSize: rf(32),
    fontFamily: 'Inter sans-serif',
    color: '#FFFFFF',
    textAlign: 'center',
    letterSpacing: rs(0.5),
  },
  getStartedButton: {
    width: '100%',
    height: hp(56),
    backgroundColor: '#FDFF8D',
    borderRadius: rs(19),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: hp(20),
    shadowColor: '#fcd6e3',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  getStartedButtonText: {
    fontSize: rf(18),
    fontFamily: 'GTMaruBold',
    
    color: '#000000',
    letterSpacing: rs(0.5),
  },
  termsContainer: {
    alignItems: 'center',
    marginTop: hp(8),
  },
  termsText: {
    fontSize: rf(12),
    fontFamily: 'Inter',
    fontWeight: '400',
    color: '#FFFFFF',
    textAlign: 'center',
    opacity: 0.85,
    lineHeight: rf(18),
  },
  termsLink: {
    textDecorationLine: 'underline',
    fontFamily: 'Inter',
    fontWeight: '600',
  },
  loaderOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 9999,
  },
  dotSpinnerContainer: {
    width: rf(50),
    height: rf(50),
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  dot: {
    position: 'absolute',
    width: rf(6),
    height: rf(14),
    borderRadius: rf(3),
    backgroundColor: '#FFFFFF',
  },
});

export default styles;
