import { StyleSheet } from 'react-native';
import { wp, hp, rf, rs } from '../utils/responsive';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  container: {
    flex: 1,
    backgroundColor: '#FFFCF1',
    position: 'relative',
  },
  progressBarContainer: {
    width: '90%',
    height: hp(8),
    borderRadius: rs(30),
    backgroundColor: '#E8E8E8',
    marginTop: hp(60),
    alignSelf: 'center',
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    backgroundColor: '#FDFF8D',
    borderTopLeftRadius: rs(30),
    borderBottomLeftRadius: rs(30),
  },
  scrollContent: {
    flexGrow: 1,
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: wp(24),
    paddingTop: hp(40),
    paddingBottom: hp(140),
  },
  headerContainer: {
    marginBottom: hp(24),
  },
  buttonContainer: {
    marginTop: hp(24),
    marginBottom: hp(32),
    width: '100%',
  },
  headerIconContainer: {
    marginBottom: hp(12),
  },
  heading: {
    fontSize: rf(24),
    fontFamily: 'GTMaruBold',
    color: '#000000',
    lineHeight: rf(32),
    marginBottom: hp(8),
  },
  subheading: {
    fontSize: rf(14),
    fontFamily: 'GTMaruRegular',
    color: '#666666',
    lineHeight: rf(20),
  },
  searchContainer: {
    marginBottom: hp(24),
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: rs(12),
    paddingHorizontal: wp(16),
    height: hp(48),
    borderWidth: rs(1),
    borderColor: '#E0E0E0',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  searchIcon: {
    marginRight: wp(12),
  },
  searchInput: {
    flex: 1,
    fontSize: rf(16),
    fontFamily: 'GTMaruRegular',
    color: '#000000',
  },
  slotsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: hp(24),
    gap: wp(12),
  },
  placeholderSlot: {
    width: wp(75),
    height: wp(75),
    borderRadius: rs(12),
    borderWidth: rs(2),
    borderStyle: 'dashed',
    borderColor: '#D0D0D0',
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectedArtistSlot: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  removeButton: {
    position: 'absolute',
    top: rs(4),
    right: rs(4),
    width: rs(24),
    height: rs(24),
    borderRadius: rs(12),
    backgroundColor: '#FF4444',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  musicNoteIcon: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  addIconContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeButtonPopular: {
    position: 'absolute',
    top: rs(4),
    right: rs(4),
    width: rs(28),
    height: rs(28),
    borderRadius: rs(14),
    backgroundColor: '#FF4444',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  artistImageContainer: {
    width: wp(50),
    height: wp(50),
    borderRadius: wp(25),
    marginBottom: hp(4),
    overflow: 'hidden',
  },
  artistImage: {
    width: '100%',
    height: '100%',
    borderRadius: wp(25),
  },
  artistImagePlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: '#E3F2FD',
    justifyContent: 'center',
    alignItems: 'center',
  },
  artistInitial: {
    fontSize: rf(20),
    fontFamily: 'GTMaruBold',
    color: '#4A90E2',
  },
  artistNameSmall: {
    fontSize: rf(10),
    fontFamily: 'GTMaruRegular',
    color: '#000000',
    textAlign: 'center',
    marginTop: hp(2),
  },
  separatorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: hp(24),
  },
  separatorLine: {
    flex: 1,
    height: rs(1),
    backgroundColor: '#E0E0E0',
  },
  separatorText: {
    marginHorizontal: wp(16),
    fontSize: rf(14),
    fontFamily: 'GTMaruRegular',
    color: '#666666',
  },
  popularSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: rs(16),
    padding: wp(16),
    marginBottom: hp(24),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: rs(1),
    borderColor: '#F0F0F0',
  },
  popularSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: hp(16),
  },
  popularSectionTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  lightbulbIcon: {
    width: rs(20),
    height: rs(20),
    marginRight: wp(8),
  },
  popularSectionTitle: {
    fontSize: rf(16),
    fontFamily: 'GTMaruBold',
    color: '#000000',
  },
  shuffleButton: {
    padding: wp(4),
  },
  popularArtistsList: {
    paddingRight: wp(16),
  },
  popularArtistCard: {
    width: wp(100),
    marginRight: wp(16),
    alignItems: 'center',
  },
  popularArtistImageContainer: {
    width: wp(100),
    height: wp(100),
    borderRadius: rs(12),
    marginBottom: hp(8),
    position: 'relative',
    overflow: 'hidden',
  },
  popularArtistImage: {
    width: '100%',
    height: '100%',
    borderRadius: rs(12),
  },
  popularArtistImagePlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: '#E3F2FD',
    justifyContent: 'center',
    alignItems: 'center',
  },
  popularArtistInitial: {
    fontSize: rf(32),
    fontFamily: 'GTMaruBold',
    color: '#4A90E2',
  },
  addButton: {
    position: 'absolute',
    top: rs(4),
    right: rs(4),
    width: rs(28),
    height: rs(28),
    borderRadius: rs(14),
    backgroundColor: '#FDFF8D',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  addedBadge: {
    position: 'absolute',
    top: rs(4),
    right: rs(4),
    width: rs(28),
    height: rs(28),
    borderRadius: rs(14),
    backgroundColor: '#4CAF50',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  popularArtistName: {
    fontSize: rf(14),
    fontFamily: 'GTMaruRegular',
    color: '#000000',
    textAlign: 'center',
  },
  continueButton: {
    width: '100%',
    height: hp(56),
    backgroundColor: '#E0E0E0',
    borderRadius: rs(12),
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  continueButtonActive: {
    backgroundColor: '#FDFF8D',
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 5,
  },
  continueButtonDisabled: {
    backgroundColor: '#E0E0E0',
    opacity: 0.6,
  },
  continueButtonText: {
    fontSize: rf(18),
    fontFamily: 'GTMaruBold',
    color: '#999999',
  },
  continueButtonTextActive: {
    color: '#000000',
  },
  continueButtonTextDisabled: {
    color: '#999999',
  },
  playlistsSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: rs(16),
    padding: wp(16),
    marginBottom: hp(24),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  playlistsSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: hp(16),
  },
  playlistsSectionTitle: {
    fontSize: rf(16),
    fontFamily: 'GTMaruBold',
    color: '#000000',
  },
  loadingIndicator: {
    marginLeft: wp(8),
  },
  playlistsList: {
    paddingRight: wp(16),
  },
  playlistCard: {
    width: wp(140),
    marginRight: wp(16),
  },
  playlistImageContainer: {
    width: wp(140),
    height: wp(140),
    borderRadius: rs(12),
    marginBottom: hp(8),
    overflow: 'hidden',
    backgroundColor: '#F5F5F5',
  },
  playlistImage: {
    width: '100%',
    height: '100%',
  },
  playlistImagePlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: '#E3F2FD',
    justifyContent: 'center',
    alignItems: 'center',
  },
  playlistName: {
    fontSize: rf(14),
    fontFamily: 'GTMaruBold',
    color: '#000000',
    marginBottom: hp(4),
    minHeight: hp(40),
  },
  playlistDescription: {
    fontSize: rf(12),
    fontFamily: 'GTMaruRegular',
    color: '#666666',
    marginBottom: hp(4),
  },
  playlistTracks: {
    fontSize: rf(11),
    fontFamily: 'GTMaruRegular',
    color: '#999999',
  },
  loadingContainer: {
    paddingVertical: hp(40),
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    fontSize: rf(14),
    fontFamily: 'GTMaruRegular',
    color: '#666666',
    marginTop: hp(12),
  },
  emptyContainer: {
    paddingVertical: hp(40),
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: {
    fontSize: rf(14),
    fontFamily: 'GTMaruRegular',
    color: '#999999',
    marginTop: hp(12),
  },
});

export default styles;

