import { StyleSheet } from 'react-native';
import { wp, hp, rf, rs } from '../utils/responsive';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  container: {
    flex: 1,
    backgroundColor: '#FFFCF1',
  },
  progressBarContainer: {
    width: '90%',
    height: hp(8),
    borderRadius: rs(30),
    backgroundColor: '#E8E8E8',
    marginTop: hp(60),
    alignSelf: 'center',
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    backgroundColor: '#FDFF8D',
    borderTopLeftRadius: rs(30),
    borderBottomLeftRadius: rs(30),
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: wp(24),
    paddingTop: hp(20),
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  cardContainer: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: rs(24),
    padding: wp(24),
    paddingTop: hp(24),
    paddingBottom: hp(32),
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
    minHeight: hp(380),
    marginTop: hp(8),
    borderWidth: rs(1),
    borderColor: '#F0F0F0',
  },
  cardHeader: {
    width: '100%',
    paddingHorizontal: wp(24),
    paddingTop: hp(20),
    paddingBottom: hp(1),
    marginBottom: hp(2),
    alignItems: 'flex-start',
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp(1),
    width: '100%',
  },
  headerIcon: {
    marginRight: wp(12),
  },
  headerIconContainer: {
    marginBottom: hp(12),
    width: rs(48),
    height: rs(48),
    borderRadius: rs(24),
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardTitle: {
    fontSize: rf(24),
    fontFamily: 'GTMaruBold',
    color: '#000000',
    flex: 1,
    lineHeight: rf(32),
   
  },
  cardSubtitle: {
    fontSize: rf(14),
    fontFamily: 'GTMaruRegular',
    color: '#666666',
    textAlign: 'left',
    lineHeight: rf(20),
    width: '100%',
    marginTop: 0,
  },
  photoContainer: {
    width: '100%',
    alignItems: 'center',
    marginBottom: hp(24),
    flex: 1,
    justifyContent: 'center',
  },
  silhouetteContainer: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    width: wp(200),
    height: wp(200),
  },
  silhouette: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#E3F2FD',
    borderRadius: rs(16),
    opacity: 0.3,
  },
  silhouettePlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  addPhotoButton: {
    position: 'absolute',
    top: '20%',
    width: rs(48),
    height: rs(48),
    borderRadius: rs(24),
  
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  addIcon: {
    width: rs(60),
    height: rs(60),
  },
  userInfoContainer: {
    position: 'absolute',
    bottom: hp(24),
    left: wp(24),
    alignItems: 'flex-start',
  },
  userInfoText: {
    fontSize: rf(18),
    fontFamily: 'GTMaruBold',
    color: '#000000',
  },
  decorativeShape1: {
    position: 'absolute',
    top: hp(20),
    right: wp(20),
    width: wp(80),
    height: wp(80),
    borderRadius: wp(40),
    backgroundColor: '#E3F2FD',
    opacity: 0.4,
  },
  decorativeShape2: {
    position: 'absolute',
    bottom: hp(60),
    right: wp(30),
    width: wp(60),
    height: wp(60),
    borderRadius: wp(30),
    backgroundColor: '#E3F2FD',
    opacity: 0.3,
  },
  decorativeShape3: {
    position: 'absolute',
    top: hp(100),
    left: wp(10),
    width: wp(50),
    height: wp(50),
    borderRadius: wp(25),
    backgroundColor: '#E3F2FD',
    opacity: 0.3,
  },
  buttonContainer: {
    width: '100%',
    paddingHorizontal: wp(24),
    paddingBottom: hp(32),
    paddingTop: hp(16),
    marginBottom: hp(62),
  },
  continueButton: {
    width: '100%',
    height: hp(56),
    backgroundColor: '#FDFF8D',
    borderRadius: rs(12),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: rs(1),
    borderColor: '#E0E0E0',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  continueButtonText: {
    fontSize: rf(18),
    fontFamily: 'GTMaruBold',
    color: 'black',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: hp(40),
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContainer: {
    width: '90%',
    maxWidth: wp(400),
    borderRadius: rs(24),
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 10,
    alignSelf: 'center',
  },
  modalContent: {
    paddingHorizontal: wp(24),
    paddingTop: hp(32),
    paddingBottom: hp(32),
  },
  modalHeader: {
    marginBottom: hp(24),
    alignItems: 'flex-start',
  },
  modalTitle: {
    fontSize: rf(22),
    fontFamily: 'GTMaruBold',
    color: '#000000',
    marginBottom: hp(8),
    lineHeight: rf(30),
  },
  modalSubtitle: {
    fontSize: rf(14),
    fontFamily: 'GTMaruRegular',
    color: '#666666',
  },
  guidelinesContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: hp(24),
  },
  guidelinesScrollView: {
    width: '100%',
    alignSelf: 'center',
  },
  guidelinesScrollContent: {
    paddingHorizontal: wp(20),
    alignItems: 'center',
    justifyContent: 'center',
  },
  guidelineCard: {
    width: wp(280),
    backgroundColor: '#FFF9C4',
    borderRadius: rs(16),
    padding: wp(24),
    marginHorizontal: wp(5),
    marginVertical: hp(8),
    minHeight: hp(140),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: rs(1),
    borderColor: '#FDFF8D',
  },
  guidelineText: {
    fontSize: rf(16),
    fontFamily: 'GTMaruRegular',
    color: '#000000',
    textAlign: 'center',
    lineHeight: rf(24),
    width: '100%',
  },
  paginationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: hp(24),
    gap: wp(8),
  },
  paginationDot: {
    width: rs(8),
    height: rs(8),
    borderRadius: rs(4),
    backgroundColor: '#E0E0E0',
  },
  paginationDotActive: {
    backgroundColor: '#FDFF8D',
    width: rs(24),
  },
  modalContinueButton: {
    width: '100%',
    height: hp(56),
    backgroundColor: '#FDFF8D',
    borderRadius: rs(12),
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  modalContinueButtonText: {
    fontSize: rf(18),
    fontFamily: 'GTMaruBold',
    color: '#000000',
  },
});

export default styles;

