import { StyleSheet } from 'react-native';
import { wp, hp, rf, rs } from '../utils/responsive';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
<<<<<<< HEAD
    backgroundColor: '#fffcf1',
  },
  container: {
    flex: 1,
    backgroundColor: '#fffcf1',
=======
    backgroundColor: '#FFFCF1',
  },
  container: {
    flex: 1,
    backgroundColor: '#FFFCF1',
>>>>>>> 872fc54bc8ac048bc29a7bd4ae86d41d25c7473f
  },
  fixedBannerBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    width: '100%',
<<<<<<< HEAD
    height: hp(600),
=======
    height: hp(500),
>>>>>>> 872fc54bc8ac048bc29a7bd4ae86d41d25c7473f
    zIndex: 0,
  },
  headerOverBanner: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(16),
    paddingTop: hp(50),
    paddingBottom: hp(16),
    backgroundColor: 'transparent',
    zIndex: 10,
  },
<<<<<<< HEAD
  headerCenter: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingRight: wp(16),
  },
  headerShareButton: {
=======
  headerShareText: {
    fontSize: rf(14),
    fontFamily: 'GTMaruMedium',
    fontWeight: '500',
    color: '#FFFFFF',
    marginLeft: wp(4),
  },
  shareButton: {
>>>>>>> 872fc54bc8ac048bc29a7bd4ae86d41d25c7473f
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp(8),
<<<<<<< HEAD
    paddingHorizontal: wp(16),
    borderRadius: rs(24),
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    gap: wp(6),
  },
  headerShareText: {
    fontSize: rf(15),
    fontFamily: 'GTMaruMedium',
    fontWeight: '500',
    color: '#FFFFFF',
=======
    paddingHorizontal: wp(14),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: rs(20),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    marginRight: wp(8),
>>>>>>> 872fc54bc8ac048bc29a7bd4ae86d41d25c7473f
  },
  headerIcon: {
    padding: wp(6),
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(4),
  },
  scrollView: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  scrollContent: {
<<<<<<< HEAD
    paddingTop: hp(110),
    paddingBottom: hp(120),
    backgroundColor: 'transparent',
  },
  imagesContainer: {
    width: '100%',
    backgroundColor: 'transparent',
    paddingHorizontal: wp(20),
    marginTop: hp(20),
  },
  imageItem: {
    width: '100%',
    marginBottom: hp(16),
  },
  gridImage: {
    width: '100%',
    height: hp(500),
    borderRadius: wp(12),
  },
  detailsContainer: {
    backgroundColor: '#fffcf1',
    paddingHorizontal: wp(20),
    paddingTop: hp(20),
    paddingBottom: hp(40),
  },
=======
    paddingTop: hp(100),
    paddingBottom: hp(120),
    backgroundColor: 'transparent',
  },
>>>>>>> 872fc54bc8ac048bc29a7bd4ae86d41d25c7473f
  bannerBackground: {
    width: '100%',
    minHeight: hp(420),
    paddingBottom: hp(20),
    justifyContent: 'flex-end',
  },
  bannerGradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: hp(300),
  },
  profilePictureSection: {
<<<<<<< HEAD
    paddingTop: hp(250),
=======
    paddingTop: hp(180),
>>>>>>> 872fc54bc8ac048bc29a7bd4ae86d41d25c7473f
    paddingBottom: hp(20),
    zIndex: 2,
    backgroundColor: 'transparent',
  },
  profileInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(20),
    marginBottom: hp(8),
    gap: wp(12),
  },
  thumbnailContainer: {
    position: 'relative',
    width: wp(64),
    height: wp(64),
  },
  thumbnailPicture: {
    width: '100%',
    height: '100%',
    borderRadius: wp(32),
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  plusIconContainer: {
    position: 'absolute',
    bottom: -wp(2),
    right: -wp(2),
    width: wp(24),
    height: wp(24),
    borderRadius: wp(12),
    backgroundColor: '#FFD700',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  plusIcon: {
    width: wp(14),
    height: wp(14),
    tintColor: '#000000',
  },
  nameVerifiedContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(6),
  },
  profileName: {
    fontSize: rf(26),
    fontFamily: 'GTMaruBold',
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  verifiedIcon: {
    marginTop: hp(2),
  },
  usernameFollowersContainer: {
    paddingHorizontal: wp(20),
<<<<<<< HEAD
    marginBottom: hp(16),
  },
  usernameFollowersText: {
    fontSize: rf(14),
    fontFamily: 'GTMaruRegular',
    fontWeight: '400',
    color: '#FFFFFF',
    opacity: 0.9,
=======
    marginBottom: hp(8),
  },
  usernameFollowersText: {
    fontSize: rf(14),
    fontFamily: 'GTMaruRegular',
    fontWeight: '400',
    color: '#FFFFFF',
    opacity: 0.9,
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(20),
    marginBottom: hp(8),
    gap: wp(6),
  },
  locationIcon: {
    marginRight: wp(2),
  },
  locationText: {
    fontSize: rf(13),
    fontFamily: 'GTMaruRegular',
    fontWeight: '400',
    color: '#FFFFFF',
    opacity: 0.85,
>>>>>>> 872fc54bc8ac048bc29a7bd4ae86d41d25c7473f
  },
  accountButtonsContainer: {
    flexDirection: 'row',
    paddingHorizontal: wp(20),
    gap: wp(12),
  },
  accountButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp(12),
    borderRadius: rs(24),
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  accountButtonActive: {
    backgroundColor: 'rgba(100, 100, 100, 0.6)',
    borderColor: 'rgba(255, 255, 255, 0.4)',
  },
  accountButtonText: {
    fontSize: rf(15),
    fontFamily: 'GTMaruMedium',
    fontWeight: '500',
    color: '#FFFFFF',
  },
  accountButtonTextActive: {
    fontFamily: 'GTMaruBold',
    fontWeight: '700',
    color: '#FFFFFF',
  },
  locationBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: wp(20),
    marginTop: hp(16),
    marginBottom: hp(12),
    paddingVertical: hp(10),
    paddingHorizontal: wp(16),
    borderRadius: rs(20),
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    gap: wp(6),
  },
  locationBarText: {
    fontSize: rf(13),
    fontFamily: 'GTMaruRegular',
    fontWeight: '400',
    color: '#FFFFFF',
    opacity: 0.85,
  },
  personalDetailsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: hp(16),
    paddingHorizontal: wp(20),
    gap: wp(8),
  },
  personalDetailsText: {
    fontSize: rf(13),
    fontFamily: 'GTMaruRegular',
    fontWeight: '400',
    color: '#FFFFFF',
    opacity: 0.85,
  },
  purpleVIcon: {
    width: wp(22),
    height: wp(22),
    borderRadius: wp(11),
    backgroundColor: '#8B5CF6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  purpleVText: {
    fontSize: rf(13),
    fontFamily: 'GTMaruBold',
    fontWeight: '700',
    color: '#FFFFFF',
  },
<<<<<<< HEAD
  noImagesContainer: {
    width: '100%',
    alignItems: 'center',
    paddingVertical: hp(60),
    backgroundColor: 'transparent',
  },
  noImagesText: {
    fontSize: rf(14),
    fontFamily: 'GTMaruRegular',
    fontWeight: '400',
    color: 'rgba(255, 255, 255, 0.5)',
  },
  // Bio Card
  bioCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: wp(12),
    padding: wp(16),
    marginBottom: hp(12),
    borderWidth: 0.5,
    borderColor: '#E5E5E5',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  sectionTitle: {
    fontSize: rf(18),
    fontFamily: 'GTMaruBold',
    fontWeight: '700',
    color: '#000000',
    marginBottom: hp(12),
  },
  bioText: {
    fontSize: rf(15),
    fontFamily: 'GTMaruRegular',
    fontWeight: '400',
    color: '#000000',
    lineHeight: rf(22),
    marginBottom: hp(12),
  },
  divider: {
    height: 1,
    backgroundColor: '#E5E5E5',
    marginVertical: hp(12),
  },
  complimentButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp(10),
    gap: wp(8),
  },
  complimentText: {
    fontSize: rf(15),
    fontFamily: 'GTMaruMedium',
    fontWeight: '600',
    color: '#000000',
  },
  // About Card
  aboutCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: wp(12),
    padding: wp(16),
    marginBottom: hp(12),
    borderWidth: 0.5,
    borderColor: '#E5E5E5',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: wp(8),
  },
  tag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    paddingHorizontal: wp(12),
    paddingVertical: hp(6),
    borderRadius: wp(16),
    marginBottom: hp(4),
    borderWidth: 0.5,
    borderColor: '#E5E5E5',
  },
  tagText: {
    fontSize: rf(14),
    fontFamily: 'GTMaruMedium',
    fontWeight: '500',
    color: '#000000',
  },
  commentButtonContainer: {
    width: '100%',
    alignItems: 'center',
    marginTop: hp(20),
    marginBottom: hp(20),
  },
  commentButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp(12),
    paddingHorizontal: wp(24),
    borderRadius: rs(24),
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E5E5E5',
    gap: wp(8),
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  commentButtonText: {
    fontSize: rf(15),
    fontFamily: 'GTMaruMedium',
    fontWeight: '600',
    color: '#000000',
=======
  storiesGridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 0,
    paddingTop: hp(16),
    gap: 0,
    backgroundColor: '#FFFCF1',
    zIndex: 5,
  },
  storyItem: {
    width: wp(393) / 3,
    marginBottom: 0,
  },
  storyImageContainer: {
    width: '100%',
    aspectRatio: 0.75,
    borderRadius: 0,
    overflow: 'hidden',
    backgroundColor: '#fffcf1',
    position: 'relative',
  },
  storyImage: {
    width: '100%',
    height: '100%',
  },
  imagesGridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: wp(20),
    paddingTop: hp(20),
    paddingBottom: hp(16),
    justifyContent: 'space-between',
    backgroundColor: '#FFFCF1',
    zIndex: 5,
  },
  imageGridItem: {
    width: '48%',
    aspectRatio: 1,
    borderRadius: rs(16),
    overflow: 'hidden',
    backgroundColor: '#F5F5F5',
    marginBottom: hp(12),
  },
  imageGridImage: {
    width: '100%',
    height: '100%',
  },
  storyTitleContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingVertical: hp(8),
    paddingHorizontal: wp(8),
    backgroundColor: 'rgba(255, 252, 241, 0.8)',
  },
  storyTitle: {
    fontSize: rf(12),
    fontFamily: 'GTMaruBold',
    fontWeight: '700',
    color: '#000000',
    textAlign: 'left',
    textTransform: 'uppercase',
  },
  noImagesContainer: {
    width: '100%',
    alignItems: 'center',
    paddingVertical: hp(60),
  },
  noImagesText: {
    fontSize: rf(14),
    fontFamily: 'GTMaruRegular',
    fontWeight: '400',
    color: '#666666',
  },
  floatingButton: {
    position: 'absolute',
    bottom: hp(100),
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFCF1',
    paddingVertical: hp(14),
    paddingHorizontal: wp(24),
    borderRadius: rs(24),
    gap: wp(8),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
    zIndex: 10,
  },
  floatingButtonText: {
    fontSize: rf(15),
    fontFamily: 'GTMaruMedium',
    fontWeight: '500',
    color: '#000000',
  },
  detailSection: {
    paddingHorizontal: wp(20),
    paddingTop: hp(24),
    paddingBottom: hp(40),
    backgroundColor: '#FFFCF1',
    zIndex: 5,
  },
  detailCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: rs(20),
    padding: wp(20),
    marginBottom: hp(16),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  detailCardTitle: {
    fontSize: rf(18),
    fontFamily: 'GTMaruBold',
    fontWeight: '700',
    color: '#000000',
    marginBottom: hp(16),
    letterSpacing: 0.2,
  },
  detailRow: {
    flexDirection: 'row',
    marginBottom: hp(12),
    alignItems: 'flex-start',
  },
  detailLabel: {
    fontSize: rf(14),
    fontFamily: 'GTMaruMedium',
    fontWeight: '500',
    color: '#666666',
    width: wp(120),
    marginRight: wp(12),
  },
  detailValue: {
    fontSize: rf(14),
    fontFamily: 'GTMaruRegular',
    fontWeight: '400',
    color: '#000000',
    flex: 1,
  },
  detailBioText: {
    fontSize: rf(14),
    fontFamily: 'GTMaruRegular',
    fontWeight: '400',
    color: '#000000',
    lineHeight: hp(22),
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: wp(8),
    marginTop: hp(4),
  },
  pillTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F8F8',
    paddingVertical: hp(10),
    paddingHorizontal: wp(14),
    borderRadius: rs(20),
    borderWidth: 0.5,
    borderColor: '#E8E8E8',
    marginBottom: hp(6),
  },
  tagIcon: {
    marginRight: wp(6),
  },
  pillTagText: {
    fontSize: rf(14),
    fontFamily: 'GTMaruMedium',
    fontWeight: '500',
    color: '#000000',
  },
  tag: {
    backgroundColor: '#F5F5F5',
    paddingVertical: hp(8),
    paddingHorizontal: wp(16),
    borderRadius: rs(20),
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  tagText: {
    fontSize: rf(13),
    fontFamily: 'GTMaruMedium',
    fontWeight: '500',
    color: '#000000',
  },
  musicArtistsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: wp(12),
    marginTop: hp(8),
    marginBottom: hp(12),
  },
  musicArtistItem: {
    alignItems: 'center',
    width: wp(80),
  },
  musicArtistImage: {
    width: wp(64),
    height: wp(64),
    borderRadius: rs(32),
    backgroundColor: '#F8F8F8',
    marginBottom: hp(6),
  },
  musicArtistImagePlaceholder: {
    width: wp(64),
    height: wp(64),
    borderRadius: rs(32),
    backgroundColor: '#F8F8F8',
    marginBottom: hp(6),
    justifyContent: 'center',
    alignItems: 'center',
  },
  musicArtistName: {
    fontSize: rf(12),
    fontFamily: 'GTMaruMedium',
    fontWeight: '500',
    color: '#000000',
    textAlign: 'center',
    maxWidth: wp(80),
>>>>>>> 872fc54bc8ac048bc29a7bd4ae86d41d25c7473f
  },
});

export default styles;