import { StyleSheet } from 'react-native';
import { wp, hp, rf, rs } from '../utils/responsive';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FFFCF1',
  },
  container: {
    flex: 1,
    backgroundColor: '#FFFCF1',
    paddingHorizontal: wp(24),
    justifyContent: 'center',

    alignItems: 'center',
  },
  titleContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: rs(16),
    paddingVertical: hp(20),
    paddingHorizontal: wp(24),
    marginBottom: hp(24),
    alignItems: 'center',
    marginTop: hp(100),
    alignSelf: 'center',
    borderWidth: 2,
    borderColor: 'grey',
    width: '100%',
  },
  title: {
    fontSize: rf(19),
    fontFamily: 'GTMaruBold',
    color: '#000000',
    lineHeight: 24,
    textAlign: 'center',
  },
  profileCard: {
    flex: 1,
    backgroundColor: '#C8E6C9',
    borderRadius: rs(24),
    padding: wp(24),
    marginBottom: hp(32),
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    minHeight: hp(400),
    overflow: 'hidden',
  },
  profileImageBackground: {
    position: 'absolute',
    top: hp(40),
    left: '50%',
    transform: [{ translateX: -rf(80) }],
    width: rf(160),
    height: rf(200),
    borderRadius: rs(20),
  },
  bubblesContainer: {
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  bubble: {
    position: 'absolute',
    backgroundColor: '#FFFFFF',
    borderRadius: rs(12),
    paddingVertical: hp(8),
    paddingHorizontal: wp(12),
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  bubbleTopLeft: {
    top: hp(50),
    left: wp(20),
    zIndex: 10,
  },
  bubbleTopRight: {
    top: hp(50),
    right: wp(20),
    zIndex: 10,
  },
  bubbleLeft: {
    top: '50%',
    left: wp(10),
    transform: [{ translateY: -hp(20) }],
    zIndex: 10,
  },
  bubbleRight: {
    top: '50%',
    right: wp(10),
    transform: [{ translateY: -hp(20) }],
    zIndex: 10,
  },
  bubbleBottomLeft: {
    bottom: hp(100),
    left: wp(20),
    zIndex: 10,
  },
  bubbleBottomRight: {
    bottom: hp(100),
    right: wp(20),
    zIndex: 10,
  },
  bubbleText: {
    fontSize: rf(14),
    fontFamily: 'Inter',
    fontWeight: '600',
    color: '#000000',
    marginLeft: wp(8),
  },
  progressBarContainer: {
    position: 'absolute',
    bottom: hp(20),
    left: wp(24),
    right: wp(24),
    height: hp(8),
    backgroundColor: '#FFFFFF',
    borderRadius: rs(4),
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
  },
  progressBar: {
    height: '100%',
    backgroundColor: '#4CAF50',
    borderRadius: rs(4),
  },
  progressCheckmark: {
    position: 'absolute',
    left: '25%',
    width: rf(20),
    height: rf(20),
    borderRadius: rf(10),
    backgroundColor: '#4CAF50',
    justifyContent: 'center',
    alignItems: 'center',
    transform: [{ translateX: -rf(10) }],
  },
  continueButton: {
    width: '100%',
    height: hp(50),
    fontWeight: 'bold',
    backgroundColor: '#FDFF8E',
    borderRadius: rs(12),
    marginTop: hp(20),
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  continueButtonText: {
    fontSize: rf(18),
    fontFamily: 'GTMaruBold',
    color: 'black',
  },
  imageContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: hp(24),
    width: '100%',
  },
  girlimage: {
    width:370,
    height: hp(470),
  },
});

export default styles;

