import { StyleSheet, Dimensions, Platform } from 'react-native';
import { hp, wp, rf, rs } from '../../../utils/responsive';

const { width: WINDOW_WIDTH, height: WINDOW_HEIGHT } = Dimensions.get('window');

const CARD_WIDTH = WINDOW_WIDTH - wp(16);
const CARD_HEIGHT = WINDOW_HEIGHT - hp(180);
const CARD_BORDER_RADIUS = 20;
const IMAGE_HEIGHT = CARD_HEIGHT; // Full card height for image - fills entire visible card area

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  
  // Header Styles
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: wp(20),
    paddingTop: Platform.OS === 'ios' ? hp(50) : hp(20),
    paddingBottom: hp(10),
    backgroundColor: '#FFFFFF',
    zIndex: 1000,
  },
  logoText: {
    fontSize: wp(41),
    fontFamily: 'GTMaruBold',
    color: '#000000',
    marginTop: hp(10),
  },
  headerIcon: {
    width: wp(40),
    height: wp(40),
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuIcon: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: hp(10),
    gap: 4,
  },
  menuIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  menuIconCircle: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#000000',
  },
  menuIconDash: {
    width: 8,
    height: 2,
    backgroundColor: '#000000',
  },

  // Card Stack
  cardStackContainer: {
    flex: 1,
    width: CARD_WIDTH,
    height: CARD_HEIGHT,
    alignSelf: 'center',
    marginTop: hp(5),
    position: 'relative',
  },
  card: {
    position: 'absolute',
    width: CARD_WIDTH,
    height: CARD_HEIGHT,
    borderRadius: CARD_BORDER_RADIUS,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E5E5E5',
  },

  // Scrollable Container Inside Card
  cardScrollContainer: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: CARD_HEIGHT,
    paddingBottom: hp(120),
    backgroundColor: 'transparent',
  },

  // Fixed Banner Background
  fixedBannerBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    width: '100%',
    height: CARD_HEIGHT,
    zIndex: 0,
  },
  bannerGradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: hp(300),
  },
  bannerOverlayContent: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingBottom: hp(40),
    paddingHorizontal: wp(20),
    zIndex: 5,
  },
  bannerProfileInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp(16),
    gap: wp(12),
  },
  bannerNameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(8),
  },
  bannerNameText: {
    fontSize: rf(28),
    fontFamily: 'GTMaruBold',
    fontWeight: '700',
    color: '#FFFFFF',
  },
  headerOverBanner: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(16),
    paddingTop: hp(50),
    paddingBottom: hp(16),
    backgroundColor: 'transparent',
    zIndex: 10,
  },
  headerCenter: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingRight: wp(16),
  },
  headerShareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp(8),
    paddingHorizontal: wp(16),
    borderRadius: rs(24),
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    gap: wp(6),
  },
  headerShareText: {
    fontSize: rf(15),
    fontFamily: 'GTMaruMedium',
    fontWeight: '500',
    color: '#FFFFFF',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(4),
  },
  profilePictureSection: {
    paddingTop: hp(20),
    paddingBottom: hp(20),
    zIndex: 2,
    backgroundColor: 'transparent',
  },
  profileInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(20),
    marginBottom: hp(8),
    gap: wp(12),
  },
  thumbnailContainer: {
    position: 'relative',
    width: wp(64),
    height: wp(64),
  },
  thumbnailPicture: {
    width: '100%',
    height: '100%',
    borderRadius: wp(32),
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  plusIconContainer: {
    position: 'absolute',
    bottom: -wp(2),
    right: -wp(2),
    width: wp(24),
    height: wp(24),
    borderRadius: wp(12),
    backgroundColor: '#FFD700',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  plusIcon: {
    width: wp(14),
    height: wp(14),
    tintColor: '#000000',
  },
  nameVerifiedContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(6),
  },
  profileName: {
    fontSize: rf(26),
    fontFamily: 'GTMaruBold',
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  verifiedIcon: {
    marginTop: hp(2),
  },
  usernameFollowersContainer: {
    paddingHorizontal: wp(20),
    marginBottom: hp(16),
  },
  usernameFollowersText: {
    fontSize: rf(14),
    fontFamily: 'GTMaruRegular',
    fontWeight: '400',
    color: '#FFFFFF',
    opacity: 0.9,
  },
  accountButtonsContainer: {
    flexDirection: 'row',
    paddingHorizontal: wp(20),
    gap: wp(12),
  },
  accountButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp(12),
    borderRadius: rs(24),
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  accountButtonActive: {
    backgroundColor: 'rgba(100, 100, 100, 0.6)',
    borderColor: 'rgba(255, 255, 255, 0.4)',
  },
  accountButtonText: {
    fontSize: rf(15),
    fontFamily: 'GTMaruMedium',
    fontWeight: '500',
    color: '#FFFFFF',
  },
  accountButtonTextActive: {
    fontFamily: 'GTMaruBold',
    fontWeight: '700',
    color: '#FFFFFF',
  },
  locationBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: wp(20),
    marginTop: hp(16),
    marginBottom: hp(12),
    paddingVertical: hp(10),
    paddingHorizontal: wp(16),
    borderRadius: rs(20),
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    gap: wp(6),
  },
  locationBarText: {
    fontSize: rf(13),
    fontFamily: 'GTMaruRegular',
    fontWeight: '400',
    color: '#FFFFFF',
    opacity: 0.85,
  },
  personalDetailsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: hp(16),
    paddingHorizontal: wp(20),
    gap: wp(8),
  },
  personalDetailsText: {
    fontSize: rf(13),
    fontFamily: 'GTMaruRegular',
    fontWeight: '400',
    color: '#FFFFFF',
    opacity: 0.85,
  },
  purpleVIcon: {
    width: wp(22),
    height: wp(22),
    borderRadius: wp(11),
    backgroundColor: '#8B5CF6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  purpleVText: {
    fontSize: rf(13),
    fontFamily: 'GTMaruBold',
    fontWeight: '700',
    color: '#FFFFFF',
  },
  imagesContainer: {
    width: '100%',
    backgroundColor: 'transparent',
    paddingHorizontal: wp(20),
    marginTop: hp(20),
  },
  imageItem: {
    width: '100%',
    marginBottom: hp(16),
  },
  gridImage: {
    width: '100%',
    height: hp(500),
    borderRadius: wp(12),
  },
  noImagesContainer: {
    width: '100%',
    alignItems: 'center',
    paddingVertical: hp(60),
    backgroundColor: 'transparent',
  },
  noImagesText: {
    fontSize: rf(14),
    fontFamily: 'GTMaruRegular',
    fontWeight: '400',
    color: 'rgba(255, 255, 255, 0.5)',
  },
  profileInfoOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: wp(20),
    paddingBottom: wp(24),
    zIndex: 5,
  },
  profileInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(0),
    marginBottom: hp(8),
    gap: wp(12),
  },
  thumbnailContainer: {
    position: 'relative',
    width: wp(64),
    height: wp(64),
  },
  thumbnailPicture: {
    width: '100%',
    height: '100%',
    borderRadius: wp(32),
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  plusIconContainer: {
    position: 'absolute',
    bottom: -wp(2),
    right: -wp(2),
    width: wp(24),
    height: wp(24),
    borderRadius: wp(12),
    backgroundColor: '#FFD700',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  plusIcon: {
    width: wp(14),
    height: wp(14),
    tintColor: '#000000',
  },
  nameVerifiedContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(6),
  },
  profileName: {
    fontSize: rf(26),
    fontFamily: 'GTMaruBold',
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  verifiedIcon: {
    marginTop: hp(2),
  },
  usernameFollowersContainer: {
    paddingHorizontal: wp(0),
    marginBottom: hp(8),
  },
  usernameFollowersText: {
    fontSize: rf(14),
    fontFamily: 'GTMaruRegular',
    fontWeight: '400',
    color: '#FFFFFF',
    opacity: 0.9,
  },
  profileLocationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(0),
    marginBottom: hp(8),
    gap: wp(6),
  },
  profileLocationIcon: {
    marginRight: wp(2),
  },
  profileLocationText: {
    fontSize: rf(13),
    fontFamily: 'GTMaruRegular',
    fontWeight: '400',
    color: '#FFFFFF',
    opacity: 0.85,
  },
  accountButtonsContainer: {
    flexDirection: 'row',
    paddingHorizontal: wp(0),
    gap: wp(12),
    marginTop: hp(8),
  },
  accountButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp(12),
    borderRadius: wp(8),
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  accountButtonText: {
    fontSize: rf(14),
    fontFamily: 'GTMaruMedium',
    fontWeight: '500',
    color: '#FFFFFF',
  },

  // Connect Button
  connectButton: {
    position: 'absolute',
    top: wp(16),
    right: wp(16),
    paddingHorizontal: wp(20),
    paddingVertical: hp(10),
    borderRadius: wp(20),
    overflow: 'hidden',
    minWidth: wp(100),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
    zIndex: 15,
  },
  connectButtonText: {
    fontSize: wp(14),
    fontWeight: '700',
    color: '#000000',
    zIndex: 2,
  },
  connectButtonGlass: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: wp(20),
  },
  androidGlassButton: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    borderRadius: wp(20),
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.9)',
  },

  // Share Button
  shareButton: {
    position: 'absolute',
    top: wp(16),
    right: wp(16),
    zIndex: 10,
  },
  shareButtonCircle: {
    width: wp(40),
    height: wp(40),
    borderRadius: wp(20),
    backgroundColor: 'rgba(100, 100, 100, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  shareIcon: {
    fontSize: wp(20),
    color: '#FFFFFF',
    fontWeight: '700',
  },

  // Details Container (Below Image)
  detailsContainer: {
    backgroundColor: '#fffcf1',
    paddingHorizontal: wp(20),
    paddingTop: hp(20),
    paddingBottom: hp(40),
  },

  // Card Sections (Bio, About, Looking For, etc.)
  bioCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: wp(12),
    padding: wp(16),
    marginBottom: hp(12),
    borderWidth: 0.5,
    borderColor: '#E5E5E5',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  aboutCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: wp(12),
    padding: wp(16),
    marginBottom: hp(12),
    borderWidth: 0.5,
    borderColor: '#E5E5E5',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  lookingForCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: wp(12),
    padding: wp(16),
    marginBottom: hp(12),
    borderWidth: 0.5,
    borderColor: '#E5E5E5',
    position: 'relative',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  locationCard: {
    backgroundColor: '#F5F5F5',
    borderRadius: wp(12),
    padding: wp(16),
    marginBottom: hp(12),
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  interestsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: wp(12),
    padding: wp(16),
    marginBottom: hp(12),
    borderWidth: 0.5,
    borderColor: '#E5E5E5',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  photosCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: wp(12),
    padding: wp(16),
    paddingBottom: wp(16),
    marginBottom: hp(12),
    borderWidth: 0.5,
    borderColor: '#E5E5E5',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },

  // Section Titles
  sectionTitle: {
    fontSize: rf(18),
    fontFamily: 'GTMaruBold',
    fontWeight: '700',
    color: '#000000',
    marginBottom: hp(12),
  },

  // Bio Section
  bioText: {
    fontSize: rf(15),
    fontFamily: 'GTMaruRegular',
    fontWeight: '400',
    color: '#000000',
    lineHeight: rf(22),
    marginBottom: hp(12),
  },
  divider: {
    height: 1,
    backgroundColor: '#E5E5E5',
    marginVertical: hp(12),
  },
  complimentButton: {
    position: 'absolute',
    bottom: hp(60),
    left: wp(16),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    paddingVertical: hp(10),
    gap: wp(8),
  },
  complimentText: {
    fontSize: rf(15),
    fontFamily: 'GTMaruMedium',
    fontWeight: '600',
    color: '#000000',
  },

  // Tags Container
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: wp(8),
  },
  tag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    paddingHorizontal: wp(12),
    paddingVertical: hp(6),
    borderRadius: wp(16),
    marginBottom: hp(4),
    borderWidth: 0.5,
    borderColor: '#E5E5E5',
  },
  tagIcon: {
    marginRight: wp(6),
  },
  tagText: {
    fontSize: rf(14),
    fontFamily: 'GTMaruMedium',
    fontWeight: '500',
    color: '#000000',
  },

  // Location Section
  locationRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: hp(12),
  },
  locationIcon: {
    fontSize: wp(18),
    marginRight: wp(10),
    marginTop: hp(2),
  },
  locationInfo: {
    flex: 1,
  },
  locationText: {
    fontSize: wp(16),
    fontWeight: '600',
    color: '#000000',
    marginBottom: hp(4),
  },
  distanceText: {
    fontSize: wp(14),
    color: '#666666',
  },
  locationButtons: {
    flexDirection: 'row',
    gap: wp(8),
  },
  locationButton: {
    backgroundColor: '#E5E5E5',
    paddingHorizontal: wp(12),
    paddingVertical: hp(8),
    borderRadius: wp(16),
  },
  locationButtonText: {
    fontSize: wp(13),
    color: '#000000',
    fontWeight: '500',
  },

  // Interests Section
  interestsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: wp(8),
  },
  interestTag: {
    backgroundColor: '#F5F5F5',
    paddingHorizontal: wp(16),
    paddingVertical: hp(8),
    borderRadius: wp(20),
    borderWidth: 0.5,
    borderColor: '#E5E5E5',
  },
  interestText: {
    fontSize: wp(14),
    color: '#333333',
    fontWeight: '500',
  },

  // Photos Grid
  photosGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: wp(8),
  },
  gridPhoto: {
    width: (CARD_WIDTH - wp(48)) / 2,
    height: wp(200),
    borderRadius: wp(12),
    backgroundColor: '#F5F5F5',
  },
  // Photos List - One photo per row
  photosList: {
    flexDirection: 'column',
    gap: hp(12),
  },
  photoItem: {
    width: '100%',
    marginBottom: hp(8),
  },
  fullWidthPhoto: {
    width: '100%',
    height: hp(450),
    borderRadius: wp(20),
    backgroundColor: '#F5F5F5',
    overflow: 'hidden',
  },

  // Bottom Navigation
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: hp(8),
    paddingBottom: Platform.OS === 'ios' ? hp(20) : hp(8),
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp(4),
  },
  navItemActive: {
    // Active state handled by label color
  },
  navIcon: {
    fontSize: wp(24),
    marginBottom: hp(2),
  },
  navLabel: {
    fontSize: wp(10),
    color: '#999999',
    fontWeight: '500',
  },
  navLabelActive: {
    color: '#000000',
    fontWeight: '700',
  },

  // Empty State
  emptyStateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: wp(32),
  },
  emptyStateText: {
    fontSize: wp(16),
    fontWeight: '600',
    color: '#999999',
    textAlign: 'center',
    marginTop: hp(16),
  },

  // Bottom Action Buttons
  bottomActionsContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    paddingBottom: Platform.OS === 'ios' ? hp(20) : hp(10),
    paddingTop: hp(12),
    borderTopWidth: 0.5,
    borderTopColor: '#E5E5E5',
    zIndex: 100,
  },
  actionButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: wp(24),
    marginBottom: hp(12),
  },
  actionButton: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  passButton: {
    width: wp(56),
    height: wp(56),
    borderRadius: wp(28),
    backgroundColor: '#000000',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  passIcon: {
    fontSize: wp(24),
    color: '#FFFFFF',
    fontWeight: '700',
  },
  superlikeButton: {
    width: wp(56),
    height: wp(56),
    borderRadius: wp(28),
    backgroundColor: '#FFD700',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  superlikeIcon: {
    fontSize: wp(24),
    color: '#000000',
    fontWeight: '700',
  },
  likeButton: {
    width: wp(56),
    height: wp(56),
    borderRadius: wp(28),
    backgroundColor: '#000000',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  likeIcon: {
    fontSize: wp(24),
    color: '#FFFFFF',
    fontWeight: '700',
  },
  commentButtonContainer: {
    width: '100%',
    alignItems: 'center',
    marginTop: hp(20),
    marginBottom: hp(20),
  },
  commentButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: hp(12),
    paddingHorizontal: wp(24),
    borderRadius: rs(24),
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E5E5E5',
    gap: wp(8),
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  commentButtonText: {
    fontSize: rf(15),
    fontFamily: 'GTMaruMedium',
    fontWeight: '600',
    color: '#000000',
  },
});

export default styles;
export { CARD_WIDTH, CARD_HEIGHT, CARD_BORDER_RADIUS, IMAGE_HEIGHT };